
Epoch 1/30

91/93 [============================>.] - ETA: 0s - loss: 0.6425 - mean_absolute_error: 0.0640
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
93/93 [==============================] - 9s 53ms/step - loss: 0.6420 - mean_absolute_error: 0.0637 - val_loss: 0.6325 - val_mean_absolute_error: 0.0354
Epoch 2/30
93/93 [==============================] - 3s 30ms/step - loss: 0.6254 - mean_absolute_error: 0.0358 - val_loss: 0.6327 - val_mean_absolute_error: 0.0379
Epoch 3/30

71/93 [=====================>........] - ETA: 0s - loss: 0.6248 - mean_absolute_error: 0.0379
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

91/93 [============================>.] - ETA: 0s - loss: 0.6254 - mean_absolute_error: 0.0367
93/93 [==============================] - 4s 49ms/step - loss: 0.6254 - mean_absolute_error: 0.0366 - val_loss: 0.6315 - val_mean_absolute_error: 0.0324
Epoch 4/30
93/93 [==============================] - 3s 30ms/step - loss: 0.6242 - mean_absolute_error: 0.0309 - val_loss: 0.6318 - val_mean_absolute_error: 0.0347
Epoch 5/30

91/93 [============================>.] - ETA: 0s - loss: 0.6249 - mean_absolute_error: 0.0343
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[34m[1mwandb[39m[22m: Adding directory to artifact (/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/wandb/run-20240212_191005-i8h37xfp/files/model-best)... Done. 0.0s
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
93/93 [==============================] - 4s 47ms/step - loss: 0.6249 - mean_absolute_error: 0.0343 - val_loss: 0.6309 - val_mean_absolute_error: 0.0306
Epoch 6/30
93/93 [==============================] - 5s 50ms/step - loss: 0.6251 - mean_absolute_error: 0.0348 - val_loss: 0.6309 - val_mean_absolute_error: 0.0289
Epoch 7/30

91/93 [============================>.] - ETA: 0s - loss: 0.6238 - mean_absolute_error: 0.0290
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
93/93 [==============================] - 5s 49ms/step - loss: 0.6238 - mean_absolute_error: 0.0290 - val_loss: 0.6306 - val_mean_absolute_error: 0.0281
Epoch 8/30
93/93 [==============================] - 3s 32ms/step - loss: 0.6242 - mean_absolute_error: 0.0314 - val_loss: 0.6309 - val_mean_absolute_error: 0.0304
Epoch 9/30

93/93 [==============================] - 3s 31ms/step - loss: 0.6240 - mean_absolute_error: 0.0310 - val_loss: 0.6309 - val_mean_absolute_error: 0.0322
Epoch 10/30
93/93 [==============================] - 3s 32ms/step - loss: 0.6235 - mean_absolute_error: 0.0288 - val_loss: 0.6310 - val_mean_absolute_error: 0.0317
Epoch 11/30

89/93 [===========================>..] - ETA: 0s - loss: 0.6237 - mean_absolute_error: 0.0287
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
93/93 [==============================] - 4s 48ms/step - loss: 0.6235 - mean_absolute_error: 0.0287 - val_loss: 0.6301 - val_mean_absolute_error: 0.0264
Epoch 12/30
 9/93 [=>............................] - ETA: 2s - loss: 0.6249 - mean_absolute_error: 0.0293

79/93 [========================>.....] - ETA: 0s - loss: 0.6231 - mean_absolute_error: 0.0288
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

91/93 [============================>.] - ETA: 0s - loss: 0.6231 - mean_absolute_error: 0.0286
93/93 [==============================] - 4s 47ms/step - loss: 0.6234 - mean_absolute_error: 0.0286 - val_loss: 0.6300 - val_mean_absolute_error: 0.0256
Epoch 13/30
93/93 [==============================] - 3s 30ms/step - loss: 0.6233 - mean_absolute_error: 0.0280 - val_loss: 0.6396 - val_mean_absolute_error: 0.0658
Epoch 14/30
93/93 [==============================] - 3s 32ms/step - loss: 0.6241 - mean_absolute_error: 0.0312 - val_loss: 0.6300 - val_mean_absolute_error: 0.0267
Epoch 15/30

93/93 [==============================] - 3s 30ms/step - loss: 0.6233 - mean_absolute_error: 0.0279 - val_loss: 0.6304 - val_mean_absolute_error: 0.0290
Epoch 16/30
93/93 [==============================] - 3s 31ms/step - loss: 0.6233 - mean_absolute_error: 0.0280 - val_loss: 0.6300 - val_mean_absolute_error: 0.0274
Epoch 17/30

85/93 [==========================>...] - ETA: 0s - loss: 0.6235 - mean_absolute_error: 0.0283
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

91/93 [============================>.] - ETA: 0s - loss: 0.6233 - mean_absolute_error: 0.0284
93/93 [==============================] - 4s 47ms/step - loss: 0.6233 - mean_absolute_error: 0.0284 - val_loss: 0.6299 - val_mean_absolute_error: 0.0256
Epoch 18/30
93/93 [==============================] - 3s 31ms/step - loss: 0.6236 - mean_absolute_error: 0.0294 - val_loss: 0.6302 - val_mean_absolute_error: 0.0275
Epoch 19/30
93/93 [==============================] - 3s 30ms/step - loss: 0.6232 - mean_absolute_error: 0.0279 - val_loss: 0.6301 - val_mean_absolute_error: 0.0278
Epoch 20/30

93/93 [==============================] - 3s 30ms/step - loss: 0.6230 - mean_absolute_error: 0.0269 - val_loss: 0.6299 - val_mean_absolute_error: 0.0266
Epoch 21/30
93/93 [==============================] - 3s 31ms/step - loss: 0.6233 - mean_absolute_error: 0.0285 - val_loss: 0.6326 - val_mean_absolute_error: 0.0406
Epoch 22/30

91/93 [============================>.] - ETA: 0s - loss: 0.6232 - mean_absolute_error: 0.0277
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
93/93 [==============================] - 4s 47ms/step - loss: 0.6232 - mean_absolute_error: 0.0277 - val_loss: 0.6298 - val_mean_absolute_error: 0.0260
Epoch 23/30
19/93 [=====>........................] - ETA: 2s - loss: 0.6271 - mean_absolute_error: 0.0278

91/93 [============================>.] - ETA: 0s - loss: 0.6232 - mean_absolute_error: 0.0289
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
93/93 [==============================] - 4s 46ms/step - loss: 0.6234 - mean_absolute_error: 0.0288 - val_loss: 0.6297 - val_mean_absolute_error: 0.0249
Epoch 24/30
 9/93 [=>............................] - ETA: 2s - loss: 0.6133 - mean_absolute_error: 0.0253

93/93 [==============================] - 3s 31ms/step - loss: 0.6231 - mean_absolute_error: 0.0275 - val_loss: 0.6298 - val_mean_absolute_error: 0.0244
Epoch 25/30
93/93 [==============================] - 3s 31ms/step - loss: 0.6231 - mean_absolute_error: 0.0274 - val_loss: 0.6300 - val_mean_absolute_error: 0.0275
Epoch 26/30

93/93 [==============================] - 3s 32ms/step - loss: 0.6229 - mean_absolute_error: 0.0265 - val_loss: 0.6307 - val_mean_absolute_error: 0.0314
Epoch 27/30
93/93 [==============================] - 3s 30ms/step - loss: 0.6230 - mean_absolute_error: 0.0272 - val_loss: 0.6299 - val_mean_absolute_error: 0.0267
Epoch 28/30

91/93 [============================>.] - ETA: 0s - loss: 0.6230 - mean_absolute_error: 0.0283
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
93/93 [==============================] - 5s 49ms/step - loss: 0.6232 - mean_absolute_error: 0.0283 - val_loss: 0.6297 - val_mean_absolute_error: 0.0251
Epoch 29/30
 9/93 [=>............................] - ETA: 2s - loss: 0.6271 - mean_absolute_error: 0.0256

93/93 [==============================] - 3s 32ms/step - loss: 0.6229 - mean_absolute_error: 0.0265 - val_loss: 0.6297 - val_mean_absolute_error: 0.0257
Epoch 30/30

93/93 [==============================] - 3s 31ms/step - loss: 0.6233 - mean_absolute_error: 0.0288 - val_loss: 0.6303 - val_mean_absolute_error: 0.0292