
[34m[1mwandb[39m[22m: [33mWARNING[39m The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
Epoch 1/30

65/66 [============================>.] - ETA: 0s - loss: 0.6609 - mean_absolute_error: 0.0909
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

66/66 [==============================] - ETA: 0s - loss: 0.6609 - mean_absolute_error: 0.0909
66/66 [==============================] - 11s 90ms/step - loss: 0.6609 - mean_absolute_error: 0.0909 - val_loss: 0.6344 - val_mean_absolute_error: 0.0409
Epoch 2/30

65/66 [============================>.] - ETA: 0s - loss: 0.6257 - mean_absolute_error: 0.0346
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
66/66 [==============================] - 4s 64ms/step - loss: 0.6258 - mean_absolute_error: 0.0346 - val_loss: 0.6322 - val_mean_absolute_error: 0.0347
Epoch 3/30

61/66 [==========================>...] - ETA: 0s - loss: 0.6242 - mean_absolute_error: 0.0317
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

66/66 [==============================] - 4s 65ms/step - loss: 0.6247 - mean_absolute_error: 0.0318 - val_loss: 0.6312 - val_mean_absolute_error: 0.0304
Epoch 4/30
66/66 [==============================] - 3s 43ms/step - loss: 0.6242 - mean_absolute_error: 0.0308 - val_loss: 0.6334 - val_mean_absolute_error: 0.0428
Epoch 5/30
35/66 [==============>...............] - ETA: 1s - loss: 0.6263 - mean_absolute_error: 0.0315
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

65/66 [============================>.] - ETA: 0s - loss: 0.6241 - mean_absolute_error: 0.0307
66/66 [==============================] - 4s 65ms/step - loss: 0.6241 - mean_absolute_error: 0.0307 - val_loss: 0.6304 - val_mean_absolute_error: 0.0276
Epoch 6/30
66/66 [==============================] - 3s 42ms/step - loss: 0.6235 - mean_absolute_error: 0.0285 - val_loss: 0.6304 - val_mean_absolute_error: 0.0291
Epoch 7/30

59/66 [=========================>....] - ETA: 0s - loss: 0.6234 - mean_absolute_error: 0.0282
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

66/66 [==============================] - 4s 64ms/step - loss: 0.6234 - mean_absolute_error: 0.0283 - val_loss: 0.6300 - val_mean_absolute_error: 0.0259
Epoch 8/30
66/66 [==============================] - 3s 42ms/step - loss: 0.6231 - mean_absolute_error: 0.0270 - val_loss: 0.6301 - val_mean_absolute_error: 0.0270
Epoch 9/30
35/66 [==============>...............] - ETA: 1s - loss: 0.6231 - mean_absolute_error: 0.0277
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

64/66 [============================>.] - ETA: 0s - loss: 0.6229 - mean_absolute_error: 0.0276
66/66 [==============================] - 4s 64ms/step - loss: 0.6232 - mean_absolute_error: 0.0275 - val_loss: 0.6300 - val_mean_absolute_error: 0.0268
Epoch 10/30
29/66 [============>.................] - ETA: 1s - loss: 0.6229 - mean_absolute_error: 0.0247
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

65/66 [============================>.] - ETA: 0s - loss: 0.6225 - mean_absolute_error: 0.0235
[34m[1mwandb[39m[22m: Adding directory to artifact (/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/wandb/run-20240212_185515-78n3z7mm/files/model-best)... Done. 0.0s
Traceback (most recent call last):
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/./train.py", line 180, in <module>
    history = train_model.train_hp(args.EPOCHS_HP, args.NUM_TRIALS_HP, args.EXECUTION_PER_TRIAL_HP, args.PATH_RESULTS)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/./train.py", line 123, in train_hp
    hp_search = hp_tuner_instance.get_hp_search(args.HP_SEARCH, args.HP_NAME)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/hyper_parameters_tuner.py", line 140, in get_hp_search
    self.tuner_search(tuner, self.callbacks[1:])
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/hyper_parameters_tuner.py", line 122, in tuner_search
    tuner.search(
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py", line 210, in search
    self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py", line 250, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py", line 215, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/hyper_parameters_tuner.py", line 58, in run_trial
    history = model.fit(
      ^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py", line 1807, in fit
    tmp_logs = self.train_function(iterator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 832, in __call__
    result = self._call(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 868, in _call
    return tracing_compilation.call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1323, in _call_flat
    return self._inference_function.call_preflattened(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/context.py", line 1486, in call_function
    outputs = execute.execute(
              ^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
66/66 [==============================] - 4s 64ms/step - loss: 0.6225 - mean_absolute_error: 0.0235 - val_loss: 0.6293 - val_mean_absolute_error: 0.0224
Epoch 11/30
33/66 [==============>...............] - ETA: 1s - loss: 0.6218 - mean_absolute_error: 0.0215